[tool.commitizen]
name = "cz_conventional_commits"
version = "0.9.21"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "commitizen"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
major_version_zero = true
annotated_tag = true
